schema_version = "1.0.0"
id = "keyframe_collection"
name = "Keyframe Collection"
version = "1.0.0"
tagline = "Allows you to add keyframes or drivers to collection visibility"
maintainer = "R4V3N"
type = "add-on"
tags = ["Animation"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]